TRUNCATE TABLE RAW.RAW_DATA;

TRUNCATE TABLE STAGING.STG_RAW_DATA;
TRUNCATE TABLE STAGING.STG_TEAMS;
TRUNCATE TABLE STAGING.STG_PLAYERS;
TRUNCATE TABLE STAGING.STG_MATCH_INFO;
TRUNCATE TABLE STAGING.STG_MATCH_INNINGS;

TRUNCATE TABLE DW.TEAMS;
TRUNCATE TABLE DW.PLAYERS;
TRUNCATE TABLE DW.MATCH_INFO;
TRUNCATE TABLE DW.MATCH_INNINGS;
