CREATE OR REPLACE TABLE DW.TEAMS (
  TEAM_ID NUMBER,
  TEAM_NAME VARCHAR(200),
  TEAM_TYPE VARCHAR(200)
);

CREATE OR REPLACE TABLE DW.PLAYERS (
  PLAYER_ID NUMBER,
  PLAYER_NAME VARCHAR(200),
  TEAMS ARRAY
);

CREATE OR REPLACE TABLE DW.MATCH_INFO (
  MATCH_ID NUMBER,
  MATCH_TYPE VARCHAR(200),
  GENDER VARCHAR(200),
  SEASON VARCHAR(200),
  CITY VARCHAR(200),
  VENUE VARCHAR(200),
  MATCH_DATE DATE,
  TEAM1_ID NUMBER,
  TEAM2_ID NUMBER,
  TOSS_WINNER_ID NUMBER,
  TOSS_DECISION VARCHAR(200),
  MATCH_WINNER_ID NUMBER,
  MARGIN VARCHAR(200),
  EVENT_NAME VARCHAR(200),
  EVENT_TYPE VARCHAR(200),
  POM_ID NUMBER,
  FILENAME VARCHAR(100)
);

CREATE OR REPLACE TABLE DW.MATCH_INNINGS (
  MATCH_ID NUMBER,
  INNING_ID NUMBER,
  OVER NUMBER,
  BATTING_TEAM NUMBER,
  BALL_IN_OVER NUMBER,
  BATTER VARCHAR(200),
  BOWLER VARCHAR(200),
  NON_STRIKER VARCHAR(200),
  RUNS_BATTER NUMBER,
  EXTRA_TYPE VARCHAR(200),
  RUNS_EXTRAS NUMBER,
  RUNS_TOTAL NUMBER,
  DISMISSAL_KIND VARCHAR(200),
  OUT_PLAYER VARCHAR(200),
  IS_POWERPLAY NUMBER(1)
);
