CREATE OR REPLACE STORAGE INTEGRATION s3_int
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = S3
  ENABLED = TRUE
  STORAGE_AWS_ROLE_ARN = '<YOUR_AWS_ROLE_ARN>'
  STORAGE_ALLOWED_LOCATIONS = ('s3://<S3 Bucket>/cricket/');

CREATE OR REPLACE STAGE s3_ext_stage
  STORAGE_INTEGRATION = s3_int
  URL = 's3://<S3 Bucket>/cricket/'
  FILE_FORMAT = (TYPE = JSON);

CREATE OR REPLACE PIPE S3_PIPE AUTO_INGEST = TRUE AS
COPY INTO RAW.RAW_DATA
FROM (SELECT $1, METADATA$FILENAME FROM @s3_ext_stage)
ON_ERROR = CONTINUE;
