CREATE OR REPLACE TABLE RAW.RAW_DATA (
  RAW_FILE VARIANT,
  FILENAME VARCHAR(100)
);

CREATE OR REPLACE TABLE RAW.DEFAULT_POWERPLAYS (
  MATCH_TYPE VARCHAR(10),
  START_OVER INT,
  END_OVER INT
);

INSERT INTO RAW.DEFAULT_POWERPLAYS VALUES 
  ('ODI', 1, 10), 
  ('T20', 1, 6);
