CREATE OR REPLACE TASK TASK_RAW_DATA
  WAREHOUSE = COMPUTE_WH
  SCHEDULE = '1 MINUTE'
  WHEN SYSTEM$STREAM_HAS_DATA('RAW.STREAM_RAW_DATA')
AS
BEGIN
  TRUNCATE TABLE STAGING.STG_RAW_DATA;
  INSERT INTO STAGING.STG_RAW_DATA
  SELECT RAW_FILE, FILENAME FROM RAW.STREAM_RAW_DATA;
END;
