CREATE OR REPLACE TABLE STAGING.STG_RAW_DATA LIKE RAW.RAW_DATA;

CREATE OR REPLACE TABLE STAGING.STG_TEAMS (
  TEAM_NAME VARCHAR(200),
  TEAM_TYPE VARCHAR(200)
);

CREATE OR REPLACE TABLE STAGING.STG_PLAYERS (
  PLAYER_NAME VARCHAR(200),
  TEAM_NAME VARCHAR(200)
);

CREATE OR REPLACE TABLE STAGING.STG_MATCH_INFO (
  MATCH_TYPE VARCHAR(200),
  GENDER VARCHAR(200),
  SEASON VARCHAR(200),
  CITY VARCHAR(200),
  VENUE VARCHAR(200),
  MATCH_DATE DATE,
  TEAM1 VARCHAR(200),
  TEAM2 VARCHAR(200),
  TOSS_WINNER VARCHAR(200),
  TOSS_DECISION VARCHAR(200),
  MATCH_WINNER VARCHAR(200),
  MARGIN VARCHAR(200),
  EVENT_NAME VARCHAR(200),
  EVENT_TYPE VARCHAR(200),
  POM VARCHAR(200),
  FILENAME VARCHAR(100)
);

CREATE OR REPLACE TABLE STAGING.STG_MATCH_INNINGS (
  INNING_ID NUMBER,
  OVER NUMBER,
  BATTING_TEAM VARCHAR(200),
  BALL_IN_OVER NUMBER,
  BATTER VARCHAR(200),
  BOWLER VARCHAR(200),
  NON_STRIKER VARCHAR(200),
  RUNS_BATTER NUMBER,
  EXTRA_TYPE VARCHAR(200),
  RUNS_EXTRAS NUMBER,
  RUNS_TOTAL NUMBER,
  DISMISSAL_KIND VARCHAR(200),
  OUT_PLAYER VARCHAR(200),
  POWERPLAYS_START_OVER FLOAT,
  POWERPLAYS_END_OVER FLOAT,
  IS_POWERPLAY NUMBER(1),
  FILENAME VARCHAR(100)
);
